### ISSUE TITLE
compton.conf file

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/next-release-notes4#1]
We should take a long and hard look at all the compton.conf we all have and decide to take one of them.
https://github.com/erikdubois/ArchLabs/blob/master/installation/personal/settings/compton/compton.conf

I have a lot applied already and maybe too much. 
Fading, shading, dimming, transparency and all is set for conky's to be beautiful

**Comment by Dobbie03** [comment]
I have merged your config.

**Comment by erikdubois** [comment]
great
