### ISSUE TITLE
Team Collaboration on the iso

### ISSUE THREAD

**Issue by ajjames31** [ARCHLabs/next-release-notes4#2]
I have a suggestion, but want to make sure everyone is cool with it. The iso source is in the archlabs-iso repo, and we should all have write access to this. The changes that need to be made for the next build can be added directly into the archlabs-iso repo as we all have time to work on it. I'm actually fairly new to Github myself, but just some things to keep in mind. 

If we push changes to the archlabs-iso repo, it will be very important to make good commit messages reference what was changed so that we all know what each other has done. We could do this by pull requests if needed, or simply by watching each other's commits. We will all also want to make sure that we pull the latest changes to our local machines before we start working, so that we have the newest changes locally. 

This is just a suggestion, but I think that it will help in using Github to it's potential. The packages to be installed will be in listed in the packages.both file in the repo. The airootfs directory is basically the file system of the iso, so config files and such will go there. If config files need to go into a user's home directory, they should be placed into /etc/skel. I hope this makes sense. What do you guys think?

**Comment by erikdubois** [comment]
sounds good - the question is to fork or not?
I was changing some stuff over at the openbox folder github. I made changes directly on the file and I made changes with a fork and then a question to pull.
Check out what I did - can you figure out what changes I made?
I do have the feeling that we need a Linus Torvalds. ONE guy that checks all commits.
Or one guy per subproject (read github) - it is not my cup of tea either. 
I work with github for some time but always alone. The power is in the collaboration. 
That is why I made some changes in the github today. Added a group and tested the project page.

**Comment by erikdubois** [comment]
I have created an iso on the basis of your github so I have read and understood the basic stuff from arch wiki.

**Comment by ajjames31** [comment]
Excellent! I agree, and I think that Matt should be the one to approve commits/pulls. Also, I may let you take over building the iso's if you are willing. I still would like to help with the project, however, as I can.

**Comment by erikdubois** [comment]
we should think indeed about backups

**Comment by erikdubois** [comment]
I want to change things but never know if I can like menu changes. Typos are no problem. 
Compton.conf change?
keyboard shortcuts... I have some to add as you know from the tutorial
I want to start but get stuck in my tracks

**Comment by Dobbie03** [comment]
Hi Guys,

Thank you Erik and Jody for kicking this off.  I have updated all the changes I have made to this repo:
https://github.com/ARCHLabs/next-release-notes4

All notes and changes have been noted, either in the readme or the AL+4 document contained with in the archive.

Can we get these changes as well as the additional applications added to the ISO please :)

Second thing I wanted to cover was "my" vision for ARCHLabs (I think Brett agrees with me here).
Bullet points is going to be the easiest way to describe this:

~ The intention was to recreate the look and feel on BunsenLabs, I want to stay true to this for as long as possible, thought with the way AL has taken off I don't know if this is possible.  Being based on Arch I think in some ways we will outstrip BL.

~ I never intended this to be a Linux newbie friendly distro, and frankly I don't care if a new Windows user doesn't install AL as it will more than likely cause us more issues than not.

- The idea was to provide the basis for the user firstly, to install Arch easily. Secondly, to have a ready to go OB desktop that looks and works perfectly.  The tools to customise are, largely, up to the user to choose and install.  

- Lastly, I wanted to share my love of Linux with the world.  

That's it really, its a basic description but for now I think it will suffice.

I am very new to GitHub so I am happy to leave this area in the hands of you more knowledgeable gentlemen.  The main thing we need now really is a repo so we can be truly a rolling release model Distro.

I hope this helps in some way.

**Comment by erikdubois** [comment]
closing this one for release 3.4.1
